name: mattermost_api_plus
description: An implementation of the Mattermost API as of 4.0.0.
version: 0.2.1
homepage: https://www.jeffmikels.com
repository: https://github.com/cntoss/mattermost_api_dart/tree/plus

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # Mattermost's API runs over standard http methods and websockets
  http: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.5
